### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brettrowberry**
Typo

### CODE REVIEW

**Comment by pimbrouwers** [comment]
Happy to give you cred for this. But can you true this up with the current docs first?

**Comment by brettrowberry** [comment]
No credit needed and I don’t have a computer handy.

**Comment by pimbrouwers** [comment]
All good! I'll correct.

Daniel Tuna and I are working on dotnet templates right now for v3. I was
thinking a REST template with swagger would be useful. You want to tackle
that?

**Comment by brettrowberry** [comment]
I’m in very early stages on a generic OpenAPI helper https://github.com/brettrowberry/okapi. At this point I’m thinking I’ll have people put an F# script in their Webroot, have them #r my yet to be created library, and when invoked, it will create the index.html and swagger.yml/swagger.json for them. No magic and all at build time. If ppl want, I could probably have the `dotnet fsi okapi.fsx` invoked by their .fsproj.

**Comment by pimbrouwers** [comment]
Cool. I'll keep my eyes peeled.

**Pull request closed without merging**
