### PR TITLE
Scope auth

### PR DESCRIPTION
**Pull request by galassie**
Hi @pimbrouwers ,
first of all, great work on this Falco, love it! :)

I see there's no support for scope authorization access control, which is very common if you integrate a service with an OIDC provider (e.g. Auth0, Okta).

The main purpose of this PR is to add Request.ifAuthenticatedWithScope.
I've also added Auth.tryFindClaim which accepts a predicate for searching a specific claim.

Of course everything is fully tested.

In addition, I've created a working example of how to create a service with this type of access control under the samples folder with some documentation on how to use it!

### CODE REVIEW

**Comment by pimbrouwers** [comment]
Good morning Enrico!

I am so glad to hear you're enjoying Falco, and much appreciate you sharing this with me!

I apologize for the delay in responding. Normally, I like to start the conversation sooner. But this has been a crazy week for me at work. 

I've done a cursory review of this PR on GitHub and it looks phenomenal. I'm hoping I get a change to dig into this on the weekend. But suffice it to say that I like the idea and love the execution!

Looking forward to working together!

**Comment by galassie** [comment]
Glad you like the PR!

I tried to keep the style consistent with the rest of code base, which I like!

I will continue to experiment with this library, if I find something interesting to discuss on, I will open an issue/discussion!

Hope to keep working on this together!

**Comment by pimbrouwers** [comment]
Dude this is great work. Amazing effort on the sample project. Seriously kudos!

I think we should create a function in the auth module called `Auth.hasScope` that accepts the issuer and scope as parameters. I think we can also make the code rely on two BCL methods and avoid the `.split`. Something like:

```fsharp
/// Returns bool if IPrincipal has specified scope
let hasScope
    (issuer : string)
    (scope : string)
    (ctx : HttpContext) : bool =
    let scopeClaim = getClaim "scope" ctx
    match scopeClaim with   
    | None       -> false
    | Some claim -> 
        strEquals claim.Issuer issuer &&        
        claim.Value.Contains(strConcat [" "; scope; " "])
```

This makes the handler look like:

```fsharp
/// Proceed if the authentication status of current IPrincipal is true
/// and has a specific scope
let ifAuthenticatedWithScope
    (issuer : string)
    (scope : string)
    (handleOk : HttpHandler)
    (handleError : HttpHandler) : HttpHandler =
    fun ctx ->
        let isAuthenticated = Auth.isAuthenticated ctx
        let hasScope = Auth.hasScope issuer scope ctx
        
        match isAuthenticated, hasScope with
        | true, true -> handleOk ctx
        | _          -> handleError ctx
```

**Comment by galassie** [comment]
Thank you!
I thought that a semi-real world example would be useful with this type of policy access!

About the changes,  I really like the idea of having a function `Auth.hasScope`, the handler is now super clean!

About the implementation of the function itself, I have some doubts:
- do you think it's possible for an IPrincipal to have multiple `scope` claims from different issuers? I don't really know honestly but if so, then we can't rely on the `Auth.getClaim` method since it gets the first claim not based on the issuer.. Otherwise the `Auth.getClaim` would result in a much cleaner implementation than the `Auth.tryFindClaim`.
-  I don't think `claim.Value.Contains(strConcat [" "; scope; " "])` is correct since the scope may contains a single value with no spaces around, or it could be at the beginning or the end.
Maybe it could be added a new function `StringUtils.strSplit`, something like

```fsharp
/// Split string into substrings based on separator
let strSplit (sep : char) (str : string) =
    str.Split([|sep|])
```

In this way, the `Auth.hasScope` would be something like

```fsharp
/// Returns bool if IPrincipal has specified scope
let hasScope
    (issuer : string)
    (scope : string)
    (ctx : HttpContext) : bool =
    tryFindClaim (fun claim -> (strEquals claim.Issuer issuer) && (strEquals claim.Type "scope")) ctx
    |> function
        | None       -> false
        | Some claim -> Array.contains scope (strSplit ' ' claim.Value)
```

or, if it's not possible/very unlikely that an IPrincipal may have more scope claims from different issuers:

```fsharp
/// Returns bool if IPrincipal has specified scope
let hasScope
    (issuer : string)
    (scope : string)
    (ctx : HttpContext) : bool =
    getClaim "scope" ctx
    |> function
        | None       -> false
        | Some claim -> 
            strEquals claim.Issuer issuer &&   
            claimIssuer Array.contains scope (strSplit ' ' claim.Value)
```

What do you think?

**Comment by pimbrouwers** [comment]
Great thinking! You're totally right. We have no choice but to predicate not only on name "scope", but also on the issuer.

I think the notion of adding an additional string util, and using the first version of "hasScope" you presented is perfect. Let'r rip!

**Comment by galassie** [comment]
Commited the changes!
Everything seems aligned! :)

**Comment by pimbrouwers** [comment]
Looks great!

My only nitpick would be to allow strSplit to accept a char array instead. Might as well expose it's full capabilities I think.

**Comment by galassie** [comment]
Done!

**Comment by pimbrouwers** [comment]
You're a beauty! Much appreciated!

Pleasure working with you, and I thank you very much for your interest in the project!

**Pull request merged**
