### PR TITLE
Add redirectPermanently and redirectTemporarily functions

### PR DESCRIPTION
**Pull request by dpraimeyuu**
This small PR makes `redirect` capability more verbose by getting rid of additional parameters required from the caller.

Before:
```fsharp
Response.redirect "/" true
```

After:
```fsharp
Response.redirectPermanentlyTo "/"
```

### CODE REVIEW

**Comment by pimbrouwers** [comment]
Did you mean to open this one? It looks to be from the same branch in your fork, `dpraimeyuu:improvement/develop-make-redirect-fun-verbose-1`.

**Comment by dpraimeyuu** [comment]
#79 is from `dpraimeyuu:improvement/make-redirect-fun-verbose-1`, whereas this PR is has different "prefix": `dpraimeyuu:improvement/develop*`.

It was just a test to check out gh action build.

**Comment by dpraimeyuu** [comment]
@pimbrouwers I removed `--no-restore` from `build.yml` (according to our Tweeter discussion) and build is now green :green_heart:

**Comment by pimbrouwers** [comment]
Much love for this. It was fun working together! Thanks for all the effort. Looking forward to doing it again.

**Pull request merged**
