### PR TITLE
Fix typos and standardize xml documentation style

### PR DESCRIPTION
**Pull request by mlaily**
(and little bonus: add a css handler for the hello world sample (`style.css` is referenced but was not served))

The documentation was a bit inconsistent. Sometimes written in the present form as it conventionally should, and sometimes written in the imperative form.

### CODE REVIEW

**Comment by pimbrouwers** [comment]
Hi Melvyn!

Thank you so much for doing this. I am totally floored! I am more than happy to merge this in ASAP. 

I do have a question though. What is the purpose of the CSS handler? I don't anticipate anyone doing this, and certainly don't want to encourage it. I would prefer they utilize the static file middleware and `wwwroot\whatever.css` which is automatically enabled. So I'm curious if there is a use case I'm missing?

**Comment by mlaily** [comment]
> I do have a question though. What is the purpose of the CSS handler?

Ah sorry, I didn't notice it was supposed to be handled by the static file middleware!  

I added this new handler because the html handler is referencing a css file that resulted in a 404 without it when I tried to load the html page.

Maybe something else is amiss then. I'll try to check again when I have time.  
Meanwhile, feel free to remove the third commit and merge only the first two if you want!

**Comment by mlaily** [comment]
Alright, it should be ok now :)

**Comment by pimbrouwers** [comment]
Simply awesome! Thank you so much for this.

**Pull request merged**
