### PR TITLE
Scriban ViewEngine sample

### PR DESCRIPTION
**Pull request by JonCanning**

### CODE REVIEW

**Comment by pimbrouwers** [comment]
This is great!

Do you mind updating the home handler to resemble something like the following? 

```fsharp
let homeHandler views : HttpHandler =
    let next model : HttpHandler = 
        fun ctx -> task {            
            let view = views |> Map.find (nameof Home)
            let! html = renderScriban model view
            return! Response.ofHtmlString html ctx
        }

    let queryMap (q : QueryCollectionReader) =
        {| Name = q.Get "name" "World"|} 
        
    Request.mapQuery queryMap next
```

That might even compile if I'm lucky today (wrote it in notepad).

**Comment by JonCanning** [comment]
Nice, I was wondering how to do it more idiomatically

**Comment by pimbrouwers** [comment]
No sweat!

Would you say that the documentation wasn't clear enough?

**Comment by JonCanning** [comment]
Maybe more to do with how my mental compiler works 🤔

**Comment by pimbrouwers** [comment]
Do you mind renaming the dir from `ViewEngine` to `Scriban`?

**Comment by JonCanning** [comment]
Didn't know you couldn't have a project and package reference with the same name

**Comment by pimbrouwers** [comment]
You're a beauty! Thank you.

**Comment by pimbrouwers** [comment]
I tried adding this to the Falco.sln and I'm getting a nuget error `nuget cycle detected Scriban -> Scriban (>= 3.0.3)` that I can't figure out. Thoughts?

**Comment by JonCanning** [comment]
Rename the folder
https://github.com/SaturnFramework/Saturn.Template/issues/7#issuecomment-376629294

**Comment by pimbrouwers** [comment]
Oooooooh. Leave it to me to do something stupid like this 🤦‍♂️

**Pull request merged**
